version: '3.8'

networks:
  pokedex_network:
    driver: bridge
    name: pokedex_network

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: pokedex
      MYSQL_USER: pokedex_service
      MYSQL_PASSWORD: 12345
    volumes:
      - ../docker/volumes/mysql:/var/lib/mysql
    networks:
      - pokedex_network

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - ../docker/volumes/redis:/data
    networks:
      - pokedex_network